spring:
  application:
    name: UTILS

  profiles:
    active: develop

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

---
spring:
  config:
    activate:
      on-profile: develop

logging:
  level:
    jdbc:
      sqlonly: debug
      sqltiming: off
      audit: off
      resultset: off
      connection: off
      resultsettable: info

---
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: off
      audit: off
      resultset: off
      connection: off
      resultsettable: off