spring:
  application:
    name: UTILS

  profiles:
    active: develop

  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mariadb://${DB_HOST}:32773/${DB_SCHEMA}?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    generate-ddl: false
    show-sql: false
    dialect: org.hibernate.dialect.MySQL5Dialect

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    displayRequestDuration: true
    tagsSorter: alpha
    url: /v3/api-docs

---
spring:
  config:
    activate:
      on-profile: develop

logging:
  level:
    jdbc:
      sqlonly: debug
      sqltiming: off
      audit: off
      resultset: off
      connection: off
      resultsettable: info

---
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: off
      audit: off
      resultset: off
      connection: off
      resultsettable: off